server:
  port: 8080

agent:
  agents:
    external-dir: /opt/agents
  skills:
    external-dir: /opt/skills-market
  owner:
    external-dir: /opt/owner
  root:
    external-dir: /opt/root
  pan:
    external-dir: /opt/pan
  teams:
    external-dir: /opt/teams
  providers:
    external-dir: /opt/registries/providers
  models:
    external-dir: /opt/registries/models
  schedule:
    external-dir: /opt/schedules
  mcp-servers:
    registry:
      external-dir: /opt/registries/mcp-servers
  viewport-servers:
    registry:
      external-dir: /opt/registries/viewport-servers

chat:
  storage:
    dir: /opt/chats

memory:
  storage:
    dir: /opt/memory
